USE student_growth;

CREATE TABLE ai_model(id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(128) NOT NULL,provider VARCHAR(32) NOT NULL,model_code VARCHAR(128) NOT NULL,api_base_url VARCHAR(512),api_key_ref VARCHAR(255),supports_vision TINYINT NOT NULL DEFAULT 0,supports_json TINYINT NOT NULL DEFAULT 1,local_flag TINYINT NOT NULL DEFAULT 0,enabled TINYINT NOT NULL DEFAULT 1,priority_no INT NOT NULL DEFAULT 100,timeout_seconds INT NOT NULL DEFAULT 120,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE KEY uk_ai_model(provider,model_code)) ENGINE=InnoDB;

CREATE TABLE prompt_template(id BIGINT PRIMARY KEY AUTO_INCREMENT,prompt_code VARCHAR(64) NOT NULL,name VARCHAR(128) NOT NULL,version_no INT NOT NULL,business_type VARCHAR(64) NOT NULL,system_prompt LONGTEXT,user_prompt_template LONGTEXT NOT NULL,output_schema JSON,status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),UNIQUE KEY uk_prompt(prompt_code,version_no)) ENGINE=InnoDB;

CREATE TABLE ai_analysis(id BIGINT PRIMARY KEY AUTO_INCREMENT,student_id BIGINT,business_type VARCHAR(64) NOT NULL,business_id BIGINT,ai_model_id BIGINT NOT NULL,prompt_template_id BIGINT,status VARCHAR(32) NOT NULL,input_summary LONGTEXT,result_json JSON,error_code VARCHAR(64),error_message TEXT,prompt_tokens INT,completion_tokens INT,duration_ms BIGINT,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),CONSTRAINT fk_aa_student FOREIGN KEY(student_id) REFERENCES student(id),CONSTRAINT fk_aa_model FOREIGN KEY(ai_model_id) REFERENCES ai_model(id),CONSTRAINT fk_aa_prompt FOREIGN KEY(prompt_template_id) REFERENCES prompt_template(id)) ENGINE=InnoDB;

CREATE TABLE attachment(id BIGINT PRIMARY KEY AUTO_INCREMENT,file_name VARCHAR(255) NOT NULL,storage_type VARCHAR(32) NOT NULL,storage_path VARCHAR(1024) NOT NULL,mime_type VARCHAR(128),file_size BIGINT NOT NULL,sha256 VARCHAR(64) NOT NULL,deleted TINYINT NOT NULL DEFAULT 0,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX idx_attachment_hash(sha256)) ENGINE=InnoDB;

CREATE TABLE ai_extraction_task(id BIGINT PRIMARY KEY AUTO_INCREMENT,task_code VARCHAR(64) NOT NULL UNIQUE,student_id BIGINT NOT NULL,subject_id BIGINT,grade_id BIGINT,source_type VARCHAR(32) NOT NULL,source_name VARCHAR(255),exam_id BIGINT,model_id BIGINT NOT NULL,prompt_template_id BIGINT,status VARCHAR(32) NOT NULL,progress_stage VARCHAR(64),progress_percent INT NOT NULL DEFAULT 0,input_type VARCHAR(32) NOT NULL,recognize_analysis TINYINT NOT NULL DEFAULT 0,match_knowledge TINYINT NOT NULL DEFAULT 1,mask_personal_info TINYINT NOT NULL DEFAULT 0,retry_count INT NOT NULL DEFAULT 0,max_retry_count INT NOT NULL DEFAULT 3,result_json JSON,error_code VARCHAR(64),error_message TEXT,started_time DATETIME(3),finished_time DATETIME(3),expire_time DATETIME(3),create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),CONSTRAINT fk_aet_student FOREIGN KEY(student_id) REFERENCES student(id),CONSTRAINT fk_aet_subject FOREIGN KEY(subject_id) REFERENCES subject(id),CONSTRAINT fk_aet_grade FOREIGN KEY(grade_id) REFERENCES grade(id),CONSTRAINT fk_aet_exam FOREIGN KEY(exam_id) REFERENCES exam(id),CONSTRAINT fk_aet_model FOREIGN KEY(model_id) REFERENCES ai_model(id),CONSTRAINT fk_aet_prompt FOREIGN KEY(prompt_template_id) REFERENCES prompt_template(id),CHECK(progress_percent BETWEEN 0 AND 100)) ENGINE=InnoDB;

CREATE TABLE ai_extraction_file(id BIGINT PRIMARY KEY AUTO_INCREMENT,task_id BIGINT NOT NULL,attachment_id BIGINT NOT NULL,page_no INT,sort_order INT NOT NULL DEFAULT 0,file_role VARCHAR(32) NOT NULL,image_width INT,image_height INT,preprocess_status VARCHAR(32),ocr_status VARCHAR(32),ocr_text LONGTEXT,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),CONSTRAINT fk_aef_task FOREIGN KEY(task_id) REFERENCES ai_extraction_task(id),CONSTRAINT fk_aef_attachment FOREIGN KEY(attachment_id) REFERENCES attachment(id)) ENGINE=InnoDB;

CREATE TABLE ai_extraction_question(id BIGINT PRIMARY KEY AUTO_INCREMENT,task_id BIGINT NOT NULL,sequence_no INT NOT NULL,page_no INT,question_no VARCHAR(64),question_type VARCHAR(32),question_text LONGTEXT NOT NULL,student_answer LONGTEXT,correct_answer LONGTEXT,answer_source VARCHAR(32),analysis_text LONGTEXT,analysis_source VARCHAR(32),error_type VARCHAR(32),difficulty TINYINT,confidence DECIMAL(5,4),status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',raw_json JSON,user_modified TINYINT NOT NULL DEFAULT 0,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),CONSTRAINT fk_aeq_task FOREIGN KEY(task_id) REFERENCES ai_extraction_task(id),UNIQUE KEY uk_aeq_task_seq(task_id,sequence_no)) ENGINE=InnoDB;

CREATE TABLE ai_extraction_question_knowledge(id BIGINT PRIMARY KEY AUTO_INCREMENT,extraction_question_id BIGINT NOT NULL,knowledge_id BIGINT,knowledge_code VARCHAR(64),knowledge_name VARCHAR(128),confidence DECIMAL(5,4),is_primary TINYINT NOT NULL DEFAULT 0,confirmed TINYINT NOT NULL DEFAULT 0,source VARCHAR(16) NOT NULL DEFAULT 'AI',create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),CONSTRAINT fk_aeqk_question FOREIGN KEY(extraction_question_id) REFERENCES ai_extraction_question(id),CONSTRAINT fk_aeqk_kn FOREIGN KEY(knowledge_id) REFERENCES knowledge_node(id)) ENGINE=InnoDB;

CREATE TABLE ai_extraction_correction(id BIGINT PRIMARY KEY AUTO_INCREMENT,task_id BIGINT NOT NULL,question_id BIGINT NOT NULL,field_name VARCHAR(64) NOT NULL,original_value LONGTEXT,corrected_value LONGTEXT,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),CONSTRAINT fk_aec_task FOREIGN KEY(task_id) REFERENCES ai_extraction_task(id),CONSTRAINT fk_aec_question FOREIGN KEY(question_id) REFERENCES ai_extraction_question(id)) ENGINE=InnoDB;
