package com.stdntedu.wrongquestion.service;

import java.time.*; import java.util.*; import java.util.function.Function; import java.util.stream.Collectors;
import com.baomidou.mybatisplus.core.toolkit.Wrappers; import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.stdntedu.base.entity.*; import com.stdntedu.base.mapper.*; import com.stdntedu.common.exception.*; import com.stdntedu.common.validation.IdConverter;
import com.stdntedu.generated.model.*; import com.stdntedu.score.entity.KnowledgeNodeReferenceEntity; import com.stdntedu.score.mapper.KnowledgeNodeReferenceMapper;
import com.stdntedu.knowledge.mastery.service.MasteryService;
import com.stdntedu.resource.service.SystemTimezoneProvider;
import com.stdntedu.student.entity.StudentEntity; import com.stdntedu.student.mapper.StudentMapper;
import com.stdntedu.wrongquestion.converter.*; import com.stdntedu.wrongquestion.entity.*; import com.stdntedu.wrongquestion.mapper.*;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service public class WrongQuestionService {
 private final WrongQuestionMapper questions; private final WrongQuestionKnowledgeMapper links; private final WrongReviewMapper reviews; private final StudentMapper students; private final SubjectMapper subjects; private final KnowledgeNodeReferenceMapper knowledge; private final DictTypeMapper dictTypes; private final DictItemMapper dictItems; private final SystemConfigReferenceMapper configs; private final WrongQuestionConverter converter; private final WrongReviewConverter reviewConverter; private final IdConverter ids; private final MasteryService mastery; private final SystemTimezoneProvider time;
 public WrongQuestionService(WrongQuestionMapper questions,WrongQuestionKnowledgeMapper links,WrongReviewMapper reviews,StudentMapper students,SubjectMapper subjects,KnowledgeNodeReferenceMapper knowledge,DictTypeMapper dictTypes,DictItemMapper dictItems,SystemConfigReferenceMapper configs,WrongQuestionConverter converter,WrongReviewConverter reviewConverter,IdConverter ids,MasteryService mastery,SystemTimezoneProvider time){this.questions=questions;this.links=links;this.reviews=reviews;this.students=students;this.subjects=subjects;this.knowledge=knowledge;this.dictTypes=dictTypes;this.dictItems=dictItems;this.configs=configs;this.converter=converter;this.reviewConverter=reviewConverter;this.ids=ids;this.mastery=mastery;this.time=time;}
 @Transactional public Wrong create(WrongCreate request){ validate(request.getStudentId(),request.getSubjectId(),request.getQuestionText(),request.getErrorType(),request.getKnowledgePoints()); WrongQuestionEntity e=converter.fromCreate(request); questions.insert(e); replaceLinks(e.getId(),request.getKnowledgePoints());mastery.recalculateAffectedMastery(e.getStudentId(),knowledgeIds(e.getId()),"CREATE_WRONG_QUESTION","WRONG_QUESTION",e.getId()); return getById(e.getId()); }
 @Transactional public Long createFromAiExtraction(WrongCreate request,String questionType,Long examId,String sourceName,LocalDate occurredDate){validate(request.getStudentId(),request.getSubjectId(),request.getQuestionText(),request.getErrorType(),request.getKnowledgePoints());WrongQuestionEntity e=converter.fromCreate(request);e.setQuestionType(questionType);e.setExamId(examId);e.setSourceName(sourceName==null?null:sourceName.substring(0,Math.min(128,sourceName.length())));e.setOccurredDate(occurredDate==null?time.today():occurredDate);e.setAnswerSource("AI");e.setAnalysisSource("AI");questions.insert(e);replaceLinks(e.getId(),request.getKnowledgePoints());return e.getId();}
 @Transactional(readOnly=true) public Wrong get(String id){return getById(ids.toLong(id));}
 @Transactional public Wrong update(String id,WrongUpdate request){ WrongQuestionEntity e=require(ids.toLong(id));Long oldStudent=e.getStudentId();Set<Long> oldKnowledge=knowledgeIds(e.getId());if(!Objects.equals(e.getVersion(),request.getVersion()))throw versionConflict();validate(request.getStudentId(),request.getSubjectId(),request.getQuestionText(),request.getErrorType(),request.getKnowledgePoints());if(request.getStatus()!=null)validateTransition(e.getStatus(),request.getStatus().getValue());converter.apply(request,e);if(request.getStatus()!=null)e.setStatus(request.getStatus().getValue());if(questions.updateById(e)==0)throw versionConflict();replaceLinks(e.getId(),request.getKnowledgePoints());Set<Long> newKnowledge=knowledgeIds(e.getId());if(Objects.equals(oldStudent,e.getStudentId())){Set<Long> affected=new HashSet<>(oldKnowledge);affected.addAll(newKnowledge);mastery.recalculateAffectedMastery(e.getStudentId(),affected,"UPDATE_WRONG_QUESTION","WRONG_QUESTION",e.getId());}else{mastery.recalculateAffectedMastery(oldStudent,oldKnowledge,"UPDATE_WRONG_QUESTION","WRONG_QUESTION",e.getId());mastery.recalculateAffectedMastery(e.getStudentId(),newKnowledge,"UPDATE_WRONG_QUESTION","WRONG_QUESTION",e.getId());}return getById(e.getId()); }
 @Transactional public void delete(String id){Long key=ids.toLong(id);WrongQuestionEntity q=require(key);Set<Long> affected=knowledgeIds(key);if(questions.deleteById(key)==0)throw new ResourceNotFoundException("wrong question not found");mastery.recalculateAffectedMastery(q.getStudentId(),affected,"DELETE_WRONG_QUESTION","WRONG_QUESTION",key);}
 @Transactional(readOnly=true) public InlineObject27AllOfData list(String studentId,int page,int size){Long student=ids.toLong(studentId);requireStudent(student);Page<WrongQuestionEntity> result=questions.selectPage(new Page<>(page,size),Wrappers.<WrongQuestionEntity>lambdaQuery().eq(WrongQuestionEntity::getStudentId,student).ne(WrongQuestionEntity::getStatus,"ARCHIVED").orderByDesc(WrongQuestionEntity::getOccurredDate).orderByDesc(WrongQuestionEntity::getCreateTime).orderByDesc(WrongQuestionEntity::getId));return page(result.getRecords(),page,size,result.getTotal());}
 @Transactional(readOnly=true) public InlineObject27AllOfData due(String studentId,OffsetDateTime before,int page,int size){Long student=ids.toLong(studentId);requireStudent(student);LocalDateTime cutoff=(before==null?time.localDateTime():time.toLocalDateTime(before));Page<WrongQuestionEntity> result=questions.selectPage(new Page<>(page,size),Wrappers.<WrongQuestionEntity>lambdaQuery().eq(WrongQuestionEntity::getStudentId,student).ne(WrongQuestionEntity::getStatus,"ARCHIVED").le(WrongQuestionEntity::getNextReviewTime,cutoff).orderByAsc(WrongQuestionEntity::getNextReviewTime).orderByAsc(WrongQuestionEntity::getCreateTime).orderByAsc(WrongQuestionEntity::getId));return page(result.getRecords(),page,size,result.getTotal());}
 @Transactional public ReviewOutcome review(String id,String idempotencyKey,ReviewCreate request){Long key=ids.toLong(id);WrongQuestionEntity q=require(key);if("ARCHIVED".equals(q.getStatus()))throw conflict("archived wrong question cannot be reviewed");if(reviews.selectCount(Wrappers.<WrongReviewEntity>lambdaQuery().eq(WrongReviewEntity::getIdempotencyKey,idempotencyKey))>0)throw conflict("duplicate review submission");WrongReviewEntity r=reviewConverter.fromCreate(key,idempotencyKey,request);int stage=nextStage(q.getReviewStage(),request.getResult());LocalDateTime next=r.getReviewTime().plusDays(intervalDays(stage));r.setNextReviewTime(next);reviews.insert(r);q.setReviewCount(q.getReviewCount()+1);q.setReviewStage(stage);q.setLastReviewTime(r.getReviewTime());q.setNextReviewTime(next);q.setStatus("REVIEWING");if(questions.updateById(q)==0)throw versionConflict();mastery.recalculateAffectedMastery(q.getStudentId(),knowledgeIds(key),"SUBMIT_WRONG_REVIEW","WRONG_REVIEW",r.getId());return new ReviewOutcome().reviewId(reviewConverter.id(r.getId())).wrongQuestionStatus(WrongStatus.REVIEWING).nextReviewTime(time.toOffsetDateTime(next));}
 private void validate(String studentId,String subjectId,String text,String errorType,List<KnowledgeLink> points){Long student=ids.toLong(studentId);Long subject=ids.toLong(subjectId);requireStudent(student);SubjectEntity s=subjects.selectById(subject);if(s==null||!Boolean.TRUE.equals(s.getEnabled()))throw validation("subject does not exist or is disabled");if(text==null||text.trim().isEmpty())throw validation("questionText is required");if(errorType!=null&&!errorType.isBlank())validateErrorType(errorType);validateKnowledge(subject,points);}
 private void validateErrorType(String code){DictTypeEntity type=dictTypes.selectOne(Wrappers.<DictTypeEntity>lambdaQuery().eq(DictTypeEntity::getDictCode,"wrong_question_error_type").eq(DictTypeEntity::getEnabled,true));if(type==null||dictItems.selectCount(Wrappers.<DictItemEntity>lambdaQuery().eq(DictItemEntity::getDictTypeId,type.getId()).eq(DictItemEntity::getItemCode,code).eq(DictItemEntity::getEnabled,true))==0)throw validation("invalid errorType");}
 private void validateKnowledge(Long subject,List<KnowledgeLink> points){if(points==null||points.isEmpty())return;Set<Long> seen=new HashSet<>();int primary=0;for(KnowledgeLink link:points){Long id=ids.toLong(link.getKnowledgeId());if(!seen.add(id))throw validation("duplicate knowledgeId");if(Boolean.TRUE.equals(link.getPrimary()))primary++;if(primary>1)throw validation("only one primary knowledge point is allowed");}Map<Long,KnowledgeNodeReferenceEntity> nodes=knowledge.selectBatchIds(seen).stream().collect(Collectors.toMap(KnowledgeNodeReferenceEntity::getId,Function.identity()));if(nodes.size()!=seen.size()||nodes.values().stream().anyMatch(node->!Boolean.TRUE.equals(node.getEnabled())||!Objects.equals(node.getSubjectId(),subject)))throw validation("knowledge node does not belong to subject");}
 private void replaceLinks(Long questionId,List<KnowledgeLink> points){links.delete(Wrappers.<WrongQuestionKnowledgeEntity>lambdaQuery().eq(WrongQuestionKnowledgeEntity::getWrongQuestionId,questionId));if(points!=null)for(KnowledgeLink link:points){WrongQuestionKnowledgeEntity e=new WrongQuestionKnowledgeEntity();e.setWrongQuestionId(questionId);e.setKnowledgeId(ids.toLong(link.getKnowledgeId()));e.setIsPrimary(Boolean.TRUE.equals(link.getPrimary()));e.setConfidence(link.getConfidence());links.insert(e);}}
 private Set<Long> knowledgeIds(Long questionId){return links.selectList(Wrappers.<WrongQuestionKnowledgeEntity>lambdaQuery().eq(WrongQuestionKnowledgeEntity::getWrongQuestionId,questionId)).stream().map(WrongQuestionKnowledgeEntity::getKnowledgeId).collect(Collectors.toSet());}
 private Wrong getById(Long id){WrongQuestionEntity q=require(id);return converter.toDto(q,links.selectList(Wrappers.<WrongQuestionKnowledgeEntity>lambdaQuery().eq(WrongQuestionKnowledgeEntity::getWrongQuestionId,id)));}
 private InlineObject27AllOfData page(List<WrongQuestionEntity> records,int p,int s,long total){Map<Long,List<WrongQuestionKnowledgeEntity>> grouped=records.isEmpty()?Map.of():links.selectList(Wrappers.<WrongQuestionKnowledgeEntity>lambdaQuery().in(WrongQuestionKnowledgeEntity::getWrongQuestionId,records.stream().map(WrongQuestionEntity::getId).toList())).stream().collect(Collectors.groupingBy(WrongQuestionKnowledgeEntity::getWrongQuestionId));return new InlineObject27AllOfData().page(p).pageSize(s).total(total).totalPages((int)((total+s-1)/s)).items(records.stream().map(q->converter.toDto(q,grouped.getOrDefault(q.getId(),List.of()))).toList());}
 private WrongQuestionEntity require(Long id){WrongQuestionEntity q=questions.selectById(id);if(q==null)throw new ResourceNotFoundException("wrong question not found");return q;} private void requireStudent(Long id){if(students.selectById(id)==null)throw new ResourceNotFoundException("student not found");}
 private int nextStage(Integer current,ReviewResult r){int stage=current==null?0:current;return switch(r){case CORRECT->Math.min(stage+1,7);case PARTIAL->stage;case WRONG,UNKNOWN->0;};}
 private long intervalDays(int stage){SystemConfigReferenceEntity config=configs.selectOne(Wrappers.<SystemConfigReferenceEntity>lambdaQuery().eq(SystemConfigReferenceEntity::getConfigKey,"review.interval.days"));if(config==null)throw new IllegalStateException("review interval configuration is missing");String[] parts=config.getConfigValue().replace("[","").replace("]","").split(",");return Long.parseLong(parts[Math.min(stage,parts.length-1)].trim());}
 private void validateTransition(String from,String to){if(from.equals(to))return;boolean allowed=switch(from){case "NEW"->Set.of("REVIEWING","ARCHIVED").contains(to);case "REVIEWING","MASTERED"->Set.of("MASTERED","ARCHIVED","REVIEWING").contains(to);case "ARCHIVED"->Set.of("NEW","REVIEWING").contains(to);default->false;};if(!allowed)throw new BusinessException("BUSINESS_RULE_VIOLATION","invalid wrong question status transition",HttpStatus.CONFLICT);}
 private BusinessException validation(String m){return new BusinessException("VALIDATION_ERROR",m,HttpStatus.UNPROCESSABLE_ENTITY);} private BusinessException conflict(String m){return new BusinessException("BUSINESS_RULE_VIOLATION",m,HttpStatus.CONFLICT);} private BusinessException versionConflict(){return new BusinessException("DATA_VERSION_CONFLICT","wrong question version conflict",HttpStatus.CONFLICT);}
}
