ALTER TABLE import_task
    DROP CHECK chk_it_status_v3,
    ADD COLUMN student_id BIGINT NULL AFTER import_type,
    ADD COLUMN options_json JSON NULL AFTER idempotency_key,
    ADD COLUMN confirm_request_json JSON NULL AFTER options_json,
    ADD COLUMN confirm_request_hash CHAR(64) NULL AFTER confirm_request_json,
    ADD COLUMN input_file_count INT NOT NULL DEFAULT 1 AFTER invalid_rows,
    ADD COLUMN warning_rows INT NOT NULL DEFAULT 0 AFTER input_file_count,
    ADD COLUMN imported_rows INT NOT NULL DEFAULT 0 AFTER warning_rows,
    ADD COLUMN skipped_rows INT NOT NULL DEFAULT 0 AFTER imported_rows,
    ADD COLUMN failed_rows INT NOT NULL DEFAULT 0 AFTER skipped_rows,
    ADD COLUMN progress_percent INT NOT NULL DEFAULT 0 AFTER failed_rows,
    ADD COLUMN retry_count INT NOT NULL DEFAULT 0 AFTER progress_percent,
    ADD COLUMN error_code VARCHAR(64) NULL AFTER error_report_attachment_id,
    ADD COLUMN error_message TEXT NULL AFTER error_code,
    ADD COLUMN started_time DATETIME(3) NULL AFTER expire_time,
    ADD COLUMN finished_time DATETIME(3) NULL AFTER started_time,
    ADD CONSTRAINT fk_it_student FOREIGN KEY(student_id) REFERENCES student(id),
    ADD CONSTRAINT chk_it_status_v21 CHECK(status IN ('UPLOADED','VALIDATING','PREVIEW_READY','CONFIRM_PENDING','IMPORTING','SUCCESS','PARTIAL_SUCCESS','FAILED','CANCELLED','EXPIRED')),
    ADD CONSTRAINT chk_it_type_v21 CHECK(import_type IN ('STUDENT','KNOWLEDGE','LEARNING_RESOURCE','SCORE','WRONG_QUESTION')),
    ADD CONSTRAINT chk_it_counts_v21 CHECK(total_rows>=0 AND valid_rows>=0 AND invalid_rows>=0 AND input_file_count BETWEEN 1 AND 20 AND warning_rows>=0 AND imported_rows>=0 AND skipped_rows>=0 AND failed_rows>=0 AND retry_count>=0 AND progress_percent BETWEEN 0 AND 100),
    ADD CONSTRAINT chk_it_confirm_hash_v21 CHECK(confirm_request_hash IS NULL OR confirm_request_hash REGEXP '^[0-9A-Fa-f]{64}$'),
    ADD INDEX idx_it_status_id(status,id),
    ADD INDEX idx_it_student_time(student_id,create_time,id);

ALTER TABLE export_task
    DROP CHECK chk_et_status_v3,
    ADD COLUMN progress_percent INT NOT NULL DEFAULT 0 AFTER include_deleted,
    ADD COLUMN error_code VARCHAR(64) NULL AFTER error_message,
    ADD COLUMN started_time DATETIME(3) NULL AFTER expire_time,
    ADD COLUMN finished_time DATETIME(3) NULL AFTER started_time,
    ADD CONSTRAINT chk_et_status_v21 CHECK(status IN ('PENDING','RUNNING','SUCCESS','FAILED','CANCELLED','EXPIRED')),
    ADD CONSTRAINT chk_et_format_v21 CHECK(export_format IN ('CSV','XLSX','JSON')),
    ADD CONSTRAINT chk_et_progress_v21 CHECK(progress_percent BETWEEN 0 AND 100),
    ADD INDEX idx_et_status_id(status,id),
    ADD INDEX idx_et_student_time(student_id,create_time,id);
