USE student_growth;

CREATE TABLE study_plan(id BIGINT PRIMARY KEY AUTO_INCREMENT,student_id BIGINT NOT NULL,title VARCHAR(255) NOT NULL,plan_type VARCHAR(32) NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',source_analysis_id BIGINT,daily_available_minutes INT,description TEXT,deleted TINYINT NOT NULL DEFAULT 0,version INT NOT NULL DEFAULT 1,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),CONSTRAINT fk_sp_student FOREIGN KEY(student_id) REFERENCES student(id),CONSTRAINT fk_sp_analysis FOREIGN KEY(source_analysis_id) REFERENCES ai_analysis(id)) ENGINE=InnoDB;

CREATE TABLE study_plan_task(id BIGINT PRIMARY KEY AUTO_INCREMENT,study_plan_id BIGINT NOT NULL,task_date DATE NOT NULL,task_type VARCHAR(32) NOT NULL,title VARCHAR(255) NOT NULL,resource_id BIGINT,wrong_question_id BIGINT,knowledge_id BIGINT,expected_duration_seconds INT,status VARCHAR(32) NOT NULL DEFAULT 'TODO',completed_time DATETIME(3),sort_order INT NOT NULL DEFAULT 0,remark TEXT,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),CONSTRAINT fk_spt_plan FOREIGN KEY(study_plan_id) REFERENCES study_plan(id),CONSTRAINT fk_spt_resource FOREIGN KEY(resource_id) REFERENCES learning_resource(id),CONSTRAINT fk_spt_wq FOREIGN KEY(wrong_question_id) REFERENCES wrong_question(id),CONSTRAINT fk_spt_kn FOREIGN KEY(knowledge_id) REFERENCES knowledge_node(id)) ENGINE=InnoDB;

CREATE TABLE recommendation(id BIGINT PRIMARY KEY AUTO_INCREMENT,student_id BIGINT NOT NULL,recommendation_type VARCHAR(32) NOT NULL,target_type VARCHAR(32) NOT NULL,target_id BIGINT,reason TEXT NOT NULL,score DECIMAL(7,4),status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',source_analysis_id BIGINT,expire_time DATETIME(3),create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),CONSTRAINT fk_rec_student FOREIGN KEY(student_id) REFERENCES student(id),CONSTRAINT fk_rec_analysis FOREIGN KEY(source_analysis_id) REFERENCES ai_analysis(id)) ENGINE=InnoDB;

CREATE TABLE growth_report(id BIGINT PRIMARY KEY AUTO_INCREMENT,student_id BIGINT NOT NULL,report_type VARCHAR(32) NOT NULL,title VARCHAR(255) NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,generation_type VARCHAR(32) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'PENDING',statistics_snapshot_json JSON,ai_analysis_id BIGINT,content_markdown LONGTEXT,deleted TINYINT NOT NULL DEFAULT 0,version INT NOT NULL DEFAULT 1,create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),CONSTRAINT fk_gr_student FOREIGN KEY(student_id) REFERENCES student(id),CONSTRAINT fk_gr_analysis FOREIGN KEY(ai_analysis_id) REFERENCES ai_analysis(id)) ENGINE=InnoDB;
