package com.stdntedu.stage5;

import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.*; import java.util.*;
import com.baomidou.mybatisplus.core.toolkit.Wrappers; import com.stdntedu.base.entity.SubjectEntity; import com.stdntedu.base.mapper.SubjectMapper; import com.stdntedu.common.exception.*; import com.stdntedu.generated.model.*; import com.stdntedu.score.entity.KnowledgeNodeReferenceEntity; import com.stdntedu.score.mapper.KnowledgeNodeReferenceMapper; import com.stdntedu.student.service.StudentService; import com.stdntedu.generated.model.StudentCreate; import com.stdntedu.wrongquestion.entity.WrongQuestionEntity; import com.stdntedu.wrongquestion.mapper.WrongQuestionMapper; import com.stdntedu.wrongquestion.service.WrongQuestionService;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.springframework.test.web.servlet.MockMvc; import org.testcontainers.containers.MySQLContainer; import org.testcontainers.junit.jupiter.*; import org.testcontainers.utility.DockerImageName;

@Testcontainers @SpringBootTest @AutoConfigureMockMvc class StageFiveIntegrationTest {
 @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>(DockerImageName.parse("mysql:8.0.36").asCompatibleSubstituteFor("mysql")).withDatabaseName("student_growth").withUsername("student_growth").withPassword("student_growth");
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);}
 @Autowired StudentService students; @Autowired SubjectMapper subjects; @Autowired KnowledgeNodeReferenceMapper nodes; @Autowired WrongQuestionMapper questions; @Autowired WrongQuestionService wrongs; @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc;

 @Test void createsPracticeAndExamSourcesAndValidatesCoreRules(){String student=student();Wrong practice=wrongs.create(create(student,subject(0),WrongSource.PRACTICE,"practice question",List.of()));Wrong exam=wrongs.create(create(student,subject(0),WrongSource.EXAM,"exam question",List.of()));assertThat(practice.getStatus()).isEqualTo(WrongStatus.NEW);assertThat(exam.getSourceType()).isEqualTo(WrongSource.EXAM);assertThatThrownBy(()->wrongs.create(create("999999",subject(0),WrongSource.PRACTICE,"bad",List.of()))).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->wrongs.create(create(student,"999999",WrongSource.PRACTICE,"bad",List.of()))).isInstanceOf(BusinessException.class);assertThatThrownBy(()->wrongs.create(create(student,subject(0),WrongSource.PRACTICE," ",List.of()))).isInstanceOf(BusinessException.class);assertThatThrownBy(()->wrongs.create(create(student,subject(0),WrongSource.PRACTICE,"bad",List.of()).errorType("NOT_A_DICT_ITEM"))).isInstanceOf(BusinessException.class);}
 @Test void createsAndReplacesKnowledgePointSets(){String student=student(), first=subject(0), second=subject(1);KnowledgeNodeReferenceEntity a=node(first),b=node(first),other=node(second);Wrong one=wrongs.create(create(student,first,WrongSource.PRACTICE,"one",List.of(link(a,true))));assertThat(one.getKnowledgePoints()).hasSize(1);Wrong many=wrongs.create(create(student,first,WrongSource.PRACTICE,"many",List.of(link(a,true),link(b,false))));assertThat(many.getKnowledgePoints()).hasSize(2);assertThatThrownBy(()->wrongs.create(create(student,first,WrongSource.PRACTICE,"missing",List.of(linkId("999999",true))))).isInstanceOf(BusinessException.class);assertThatThrownBy(()->wrongs.create(create(student,first,WrongSource.PRACTICE,"other",List.of(link(other,true))))).isInstanceOf(BusinessException.class);assertThatThrownBy(()->wrongs.create(create(student,first,WrongSource.PRACTICE,"dup",List.of(link(a,true),link(a,false))))).isInstanceOf(BusinessException.class);Wrong updated=wrongs.update(many.getId(),update(many,first,"many changed",List.of(link(b,true))));assertThat(updated.getKnowledgePoints()).extracting(KnowledgeLink::getKnowledgeId).containsExactly(b.getId().toString());}
 @Test void getsListsUpdatesAndDeletesWithOptimisticLock(){String student=student(), sub=subject(0);Wrong created=wrongs.create(create(student,sub,WrongSource.PRACTICE,"search text",List.of()));assertThat(wrongs.get(created.getId()).getId()).matches("[0-9]+");assertThatThrownBy(()->wrongs.get("999999")).isInstanceOf(ResourceNotFoundException.class);assertThat(wrongs.list(student,1,20).getItems()).extracting(Wrong::getId).contains(created.getId());WrongUpdate first=update(created,sub,"changed",List.of());Wrong changed=wrongs.update(created.getId(),first);assertThat(changed.getVersion()).isEqualTo(created.getVersion()+1);assertThatThrownBy(()->wrongs.update(created.getId(),first)).isInstanceOf(BusinessException.class).satisfies(e->assertThat(((BusinessException)e).getCode()).isEqualTo("DATA_VERSION_CONFLICT"));wrongs.delete(created.getId());assertThatThrownBy(()->wrongs.get(created.getId())).isInstanceOf(ResourceNotFoundException.class);assertThat(wrongs.list(student,1,20).getItems()).extracting(Wrong::getId).doesNotContain(created.getId());}
 @Test void validatesExplicitStatusTransitions(){String student=student(),sub=subject(0);Wrong created=wrongs.create(create(student,sub,WrongSource.PRACTICE,"state",List.of()));assertThatThrownBy(()->wrongs.update(created.getId(),update(created,sub,"state",List.of()).status(WrongStatus.MASTERED))).isInstanceOf(BusinessException.class);Wrong reviewing=wrongs.update(created.getId(),update(created,sub,"state",List.of()).status(WrongStatus.REVIEWING));Wrong mastered=wrongs.update(reviewing.getId(),update(reviewing,sub,"state",List.of()).status(WrongStatus.MASTERED));Wrong archived=wrongs.update(mastered.getId(),update(mastered,sub,"state",List.of()).status(WrongStatus.ARCHIVED));assertThat(wrongs.list(student,1,20).getItems()).extracting(Wrong::getId).doesNotContain(archived.getId());assertThat(wrongs.update(archived.getId(),update(archived,sub,"state",List.of()).status(WrongStatus.NEW)).getStatus()).isEqualTo(WrongStatus.NEW);}
 @Test void submitsReviewsSchedulesNextTimeAndDoesNotWriteMastery(){String student=student(),sub=subject(0);Wrong q=wrongs.create(create(student,sub,WrongSource.PRACTICE,"review",List.of()));int masteryBefore=jdbc.queryForObject("select count(*) from student_mastery",Integer.class),historyBefore=jdbc.queryForObject("select count(*) from mastery_history",Integer.class);for(ReviewResult result:ReviewResult.values()){ReviewOutcome outcome=wrongs.review(q.getId(),"review-key-"+result.getValue(),review(result));assertThat(outcome.getReviewId()).matches("[0-9]+");assertThat(outcome.getWrongQuestionStatus()).isEqualTo(WrongStatus.REVIEWING);assertThat(outcome.getNextReviewTime()).isNotNull();}WrongQuestionEntity stored=questions.selectById(Long.valueOf(q.getId()));assertThat(stored.getReviewCount()).isEqualTo(4);assertThat(stored.getLastReviewTime()).isNotNull();assertThat(stored.getNextReviewTime()).isNotNull();assertThat(stored.getReviewStage()).isBetween(0,7);assertThatThrownBy(()->wrongs.review(q.getId(),"review-key-CORRECT",review(ReviewResult.CORRECT))).isInstanceOf(BusinessException.class);assertThat(jdbc.queryForObject("select count(*) from student_mastery",Integer.class)).isEqualTo(masteryBefore);assertThat(jdbc.queryForObject("select count(*) from mastery_history",Integer.class)).isEqualTo(historyBefore);}
 @Test void returnsOnlyDueNonArchivedAndNonDeletedQuestions(){String student=student(),sub=subject(0);Wrong due=wrongs.create(create(student,sub,WrongSource.PRACTICE,"due",List.of()));Wrong future=wrongs.create(create(student,sub,WrongSource.PRACTICE,"future",List.of()));Wrong archived=wrongs.create(create(student,sub,WrongSource.PRACTICE,"archive",List.of()));setNext(future,LocalDateTime.now().plusDays(3));wrongs.update(archived.getId(),update(archived,sub,"archive",List.of()).status(WrongStatus.ARCHIVED));wrongs.delete(future.getId());assertThat(wrongs.due(student,OffsetDateTime.now().plusMinutes(1),1,20).getItems()).extracting(Wrong::getId).contains(due.getId()).doesNotContain(future.getId(),archived.getId());}
 @Test void exposesHttpRequestIdUnifiedErrorsAndStringIds() throws Exception {String student=student();Wrong q=wrongs.create(create(student,subject(0),WrongSource.PRACTICE,"http",List.of()));mvc.perform(get("/api/v1/wrong-questions/{id}",q.getId()).header("X-Request-ID","stage5-http")).andExpect(status().isOk()).andExpect(header().string("X-Request-ID","stage5-http")).andExpect(jsonPath("$.requestId").value("stage5-http")).andExpect(jsonPath("$.data.id").isString()).andExpect(jsonPath("$.data.studentId").isString());mvc.perform(get("/api/v1/wrong-questions/999999")).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("NOT_FOUND"));mvc.perform(post("/api/v1/wrong-questions").contentType("application/json").content("{}")).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.data.fieldErrors").isArray());}
 @Test void createsPracticeQuestionAsNew(){Wrong q=wrongs.create(create(student(),subject(0),WrongSource.PRACTICE,"practice",List.of()));assertThat(q.getStatus()).isEqualTo(WrongStatus.NEW);}
 @Test void createsExamSourceQuestion(){Wrong q=wrongs.create(create(student(),subject(0),WrongSource.EXAM,"exam",List.of()));assertThat(q.getSourceType()).isEqualTo(WrongSource.EXAM);}
 @Test void rejectsUnknownStudentOnCreate(){assertThatThrownBy(()->wrongs.create(create("999999",subject(0),WrongSource.PRACTICE,"bad",List.of()))).isInstanceOf(ResourceNotFoundException.class);}
 @Test void rejectsUnknownSubjectOnCreate(){assertThatThrownBy(()->wrongs.create(create(student(),"999999",WrongSource.PRACTICE,"bad",List.of()))).isInstanceOf(BusinessException.class);}
 @Test void rejectsBlankQuestionText(){assertThatThrownBy(()->wrongs.create(create(student(),subject(0),WrongSource.PRACTICE," ",List.of()))).isInstanceOf(BusinessException.class);}
 @Test void rejectsUnknownErrorType(){assertThatThrownBy(()->wrongs.create(create(student(),subject(0),WrongSource.PRACTICE,"bad",List.of()).errorType("NOT_A_DICT_ITEM"))).isInstanceOf(BusinessException.class);}
 @Test void rejectsMissingKnowledgeNode(){assertThatThrownBy(()->wrongs.create(create(student(),subject(0),WrongSource.PRACTICE,"bad",List.of(linkId("999999",true))))).isInstanceOf(BusinessException.class);}
 @Test void rejectsKnowledgeNodeFromAnotherSubject(){String first=subject(0),second=subject(1);assertThatThrownBy(()->wrongs.create(create(student(),first,WrongSource.PRACTICE,"bad",List.of(link(node(second),true))))).isInstanceOf(BusinessException.class);}
 @Test void rejectsDuplicateKnowledgeNode(){String sub=subject(0);KnowledgeNodeReferenceEntity n=node(sub);assertThatThrownBy(()->wrongs.create(create(student(),sub,WrongSource.PRACTICE,"bad",List.of(link(n,true),link(n,false))))).isInstanceOf(BusinessException.class);}
 @Test void persistsMultipleKnowledgeNodes(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"linked",List.of(link(node(sub),true),link(node(sub),false))));assertThat(q.getKnowledgePoints()).hasSize(2);}
 @Test void updatesKnowledgeNodeSetByReplacement(){String sub=subject(0);KnowledgeNodeReferenceEntity one=node(sub),two=node(sub);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"linked",List.of(link(one,true))));Wrong updated=wrongs.update(q.getId(),update(q,sub,"changed",List.of(link(two,true))));assertThat(updated.getKnowledgePoints()).extracting(KnowledgeLink::getKnowledgeId).containsExactly(two.getId().toString());}
 @Test void returnsNotFoundForMissingQuestion(){assertThatThrownBy(()->wrongs.get("999999")).isInstanceOf(ResourceNotFoundException.class);}
 @Test void incrementsVersionOnUpdate(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"version",List.of()));assertThat(wrongs.update(q.getId(),update(q,sub,"changed",List.of())).getVersion()).isEqualTo(q.getVersion()+1);}
 @Test void rejectsStaleVersionWithConflictCode(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"version",List.of()));WrongUpdate request=update(q,sub,"changed",List.of());wrongs.update(q.getId(),request);assertThatThrownBy(()->wrongs.update(q.getId(),request)).isInstanceOf(BusinessException.class).satisfies(e->assertThat(((BusinessException)e).getCode()).isEqualTo("DATA_VERSION_CONFLICT"));}
 @Test void logicallyDeletesQuestionAndHidesIt(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"delete",List.of()));wrongs.delete(q.getId());assertThatThrownBy(()->wrongs.get(q.getId())).isInstanceOf(ResourceNotFoundException.class);}
 @Test void rejectsInvalidNewToMasteredTransition(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"state",List.of()));assertThatThrownBy(()->wrongs.update(q.getId(),update(q,sub,"state",List.of()).status(WrongStatus.MASTERED))).isInstanceOf(BusinessException.class);}
 @Test void hidesArchivedQuestionAndAllowsRestoreToNew(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"archive",List.of()));Wrong archived=wrongs.update(q.getId(),update(q,sub,"archive",List.of()).status(WrongStatus.ARCHIVED));assertThat(wrongs.list(q.getStudentId(),1,20).getItems()).extracting(Wrong::getId).doesNotContain(q.getId());assertThat(wrongs.update(archived.getId(),update(archived,sub,"restore",List.of()).status(WrongStatus.NEW)).getStatus()).isEqualTo(WrongStatus.NEW);}
 @Test void correctReviewAdvancesSchedule(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"correct",List.of()));wrongs.review(q.getId(),"correct-"+UUID.randomUUID(),review(ReviewResult.CORRECT));assertThat(questions.selectById(Long.valueOf(q.getId())).getReviewStage()).isEqualTo(1);}
 @Test void partialReviewKeepsInitialStage(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"partial",List.of()));wrongs.review(q.getId(),"partial-"+UUID.randomUUID(),review(ReviewResult.PARTIAL));assertThat(questions.selectById(Long.valueOf(q.getId())).getReviewStage()).isZero();}
 @Test void wrongReviewResetsStage(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"wrong",List.of()));wrongs.review(q.getId(),"wrong-"+UUID.randomUUID(),review(ReviewResult.WRONG));assertThat(questions.selectById(Long.valueOf(q.getId())).getReviewStage()).isZero();}
 @Test void unknownReviewResetsStage(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"unknown",List.of()));wrongs.review(q.getId(),"unknown-"+UUID.randomUUID(),review(ReviewResult.UNKNOWN));assertThat(questions.selectById(Long.valueOf(q.getId())).getReviewStage()).isZero();}
 @Test void rejectsDuplicateReviewIdempotencyKey(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"idempotent",List.of()));String key="idempotent-"+UUID.randomUUID();wrongs.review(q.getId(),key,review(ReviewResult.CORRECT));assertThatThrownBy(()->wrongs.review(q.getId(),key,review(ReviewResult.CORRECT))).isInstanceOf(BusinessException.class);}
 @Test void reviewDoesNotWriteMasteryTables(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"no mastery",List.of()));int mastery=jdbc.queryForObject("select count(*) from student_mastery",Integer.class),history=jdbc.queryForObject("select count(*) from mastery_history",Integer.class);wrongs.review(q.getId(),"mastery-"+UUID.randomUUID(),review(ReviewResult.CORRECT));assertThat(jdbc.queryForObject("select count(*) from student_mastery",Integer.class)).isEqualTo(mastery);assertThat(jdbc.queryForObject("select count(*) from mastery_history",Integer.class)).isEqualTo(history);}
 @Test void returnsCurrentDueQuestion(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"due",List.of()));assertThat(wrongs.due(q.getStudentId(),OffsetDateTime.now().plusMinutes(1),1,20).getItems()).extracting(Wrong::getId).contains(q.getId());}
 @Test void excludesFutureQuestionFromDueList(){String sub=subject(0);Wrong q=wrongs.create(create(student(),sub,WrongSource.PRACTICE,"future",List.of()));setNext(q,LocalDateTime.now().plusDays(1));assertThat(wrongs.due(q.getStudentId(),OffsetDateTime.now(),1,20).getItems()).extracting(Wrong::getId).doesNotContain(q.getId());}
 @Test void returnsRequestIdHeaderAndBody(){String student=student();Wrong q=wrongs.create(create(student,subject(0),WrongSource.PRACTICE,"http header",List.of()));assertThatCode(()->mvc.perform(get("/api/v1/wrong-questions/{id}",q.getId()).header("X-Request-ID","stage5-unique")).andExpect(status().isOk()).andExpect(header().string("X-Request-ID","stage5-unique")).andExpect(jsonPath("$.requestId").value("stage5-unique"))).doesNotThrowAnyException();}
 @Test void returnsFieldErrorsForInvalidHttpCreate() throws Exception {mvc.perform(post("/api/v1/wrong-questions").contentType("application/json").content("{}")).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.data.fieldErrors").isArray());}
 private String student(){return students.create(new StudentCreate().name("stage5 "+UUID.randomUUID()).currentStageId("1").currentGradeId("1")).getId();} private String subject(int i){return subjects.selectList(null).stream().filter(SubjectEntity::getEnabled).skip(i).findFirst().orElseThrow().getId().toString();}
 private KnowledgeNodeReferenceEntity node(String subject){KnowledgeNodeReferenceEntity n=new KnowledgeNodeReferenceEntity();n.setNodeCode("S5-"+UUID.randomUUID());n.setName("node");n.setNodeType("KNOWLEDGE_POINT");n.setSubjectId(Long.valueOf(subject));n.setEnabled(true);n.setDeleted(false);nodes.insert(n);return n;} private KnowledgeLink link(KnowledgeNodeReferenceEntity n,boolean primary){return linkId(n.getId().toString(),primary);} private KnowledgeLink linkId(String id,boolean primary){return new KnowledgeLink().knowledgeId(id).primary(primary);}
 private WrongCreate create(String student,String subject,WrongSource source,String text,List<KnowledgeLink> links){return new WrongCreate().studentId(student).subjectId(subject).sourceType(source).questionText(text).knowledgePoints(links);} private WrongUpdate update(Wrong w,String subject,String text,List<KnowledgeLink> links){return new WrongUpdate().studentId(w.getStudentId()).subjectId(subject).sourceType(w.getSourceType()).questionText(text).studentAnswer(w.getStudentAnswer()).correctAnswer(w.getCorrectAnswer()).analysisText(w.getAnalysisText()).errorType(w.getErrorType()).difficulty(w.getDifficulty()).knowledgePoints(links).version(w.getVersion());} private ReviewCreate review(ReviewResult result){return new ReviewCreate().reviewTime(OffsetDateTime.now()).result(result).durationSeconds(30);} private void setNext(Wrong w,LocalDateTime t){WrongQuestionEntity e=questions.selectById(Long.valueOf(w.getId()));e.setNextReviewTime(t);questions.updateById(e);}
}
