spring:
  datasource:
    url: jdbc:tc:mysql:8.0.36:///student_growth?TC_TMPFS=/var/lib/mysql:rw
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
